FROM node:bullseye

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Clone game source code
#RUN git clone https://github.com/font/pacman.git .
COPY . /usr/src/app/

# Install app dependencies
RUN npm install

# Expose port 8080
EXPOSE 8080

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

# Run container
CMD ["npm", "start"]
