FROM node:bullseye

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Clone game source code
#RUN git clone https://github.com/c2codes/pacman-splunk.git .
COPY . /usr/src/app/

# Install app dependencies
RUN npm install

# Expose port 8080
EXPOSE 8080

RUN chmod +x start.sh

# Run container
CMD ["bash","-c","./start.sh"]
